name: "Build container image"
description: "Action for building a container image, or restoring it from
  cache if such exists."
author: "The Dev Nolus Team <dev@nolus.io>"

inputs:
  profile:
    description: ""
    required: false
  target:
    description: ""
    required: true
  tools-context:
    default: "false"
    description: ""
    required: false
  workspace:
    description: ""
    required: false

runs:
  using: "composite"
  steps:
    - id: "build-container"
      uses: "./.github/actions/build-image"
      with:
        build-contexts: |-
          ${{ (fromJSON(inputs.tools-context) && 'tools="./tools"') || '' }}
        target: |-
          ${{ inputs.target }}
    - env:
        image_tag: |-
          ${{ steps.build-container.outputs.tag }}
      run: |-
        set -eu

        "docker" \
          "container" \
          "run" \
          ${{ (inputs.profile && format('--env "PROFILE={0}"', inputs.profile)) || '' }} \
          --rm \
          --tty \
          --volume ".:/src:ro" \
          "${image_tag:?}" \
          ${{ (inputs.workspace && format('"{0}"', inputs.workspace)) || '' }}
      shell: "sh"
