lints = { workspace = true }

[package]
name = "tree"
version = "0.1.0"
edition.workspace = true
authors.workspace = true
license.workspace = true

[package.metadata.cargo-each]
combinations = [
    { tags = ["ci", "@agnostic"], include-rest = true },
]

[features]
schema = ["dep:sdk", "sdk/schema"]
testing = []

[dependencies]
sdk = { workspace = true, optional = true, features = ["schema"] }

serde = { workspace = true, features = ["std", "derive"] }

[dev-dependencies]
sdk = { workspace = true }
