lints = { workspace = true }

[package]
name = "versioning"
version = "0.2.1"
edition.workspace = true
authors.workspace = true
license.workspace = true

[package.metadata.cargo-each]
combinations = [
    { tags = ["ci", "@agnostic"], include-rest = true },
]

[features]
protocol_contract = []
schema = ["sdk/schema"]
testing = []

[dependencies]
sdk = { workspace = true, features = ["schema", "storage"] }

thiserror = { workspace = true }
serde = { workspace = true, features = ["derive"] }
