[package]
name = "currencies"
version = "0.1.0"
authors = ["The Dev Nolus Team <dev@nolus.io>"]
edition.workspace = true
license.workspace = true

[lib]
doctest = false

[features]
net_dev = []
net_test = []
net_main = []

astroport = []
osmosis = []

testing = []

[dependencies]
currency = { workspace = true }
sdk = { workspace = true, features = ["schema"] }
compile_time_sha2 = { workspace = true }

thiserror = { workspace = true }
serde = { workspace = true, features = ["derive"] }

[dev-dependencies]
currency = { workspace = true, features = ["testing"] }
