[package]
name = "json-value"
version = "0.0.0"
edition.workspace = true
authors.workspace = true
license.workspace = true

[features]
schema = ["dep:sdk"]

[dependencies]
# Own packages
sdk = { workspace = true, optional = true, features = ["schema"] }

# General packages
serde = { workspace = true }

[dev-dependencies]
# Own packages
either = { workspace = true }

# General packages
serde_json = { workspace = true }
serde_test = { workspace = true }

[lints]
workspace = true
