name: "Build container image"
description: "Action for building a container image, or restoring it from
  cache if such exists."
author: "The Dev Nolus Team <dev@nolus.io>"

inputs:
  target:
    description: ""
    required: true
  build-arguments:
    description: ""
    required: false
  build-contexts:
    description: ""
    required: false

outputs:
  tag:
    description: ""
    value: |-
      ${{ steps.tag.outputs.tag }}

runs:
  using: "composite"
  steps:
    - env:
        image_tag: |-
          ${{ inputs.target }}
      id: "tag"
      run: |-
        set -eu

        "echo" "tag<<EOF
        localhost/local/${image_tag:?}
        EOF" >>"${GITHUB_OUTPUT:?}"
      shell: "sh"
    - env:
        DOCKER_BUILD_RECORD_UPLOAD: "false"
        DOCKER_BUILD_SUMMARY: "false"
        SOURCE_DATE_EPOCH: "0"
      id: "build-container"
      uses: "docker/build-push-action@v6"
      with:
        build-args: |-
          ${{ inputs.build-arguments || '' }}
        build-contexts: |-
          ${{ inputs.build-contexts || '' }}
        cache-from: |-
          type=gha,scope=${{ inputs.target }}
        cache-to: |-
          type=gha,mode=max,scope=${{ inputs.target }}
        context: "./ci/"
        file: "./Containerfile"
        outputs: "type=docker,rewrite-timestamp=true"
        provenance: false
        tags: |-
          ${{ steps.tag.outputs.tag }}
        target: |-
          ${{ inputs.target }}
