name: "Build container image"
description: "Action for building a container image, or restoring it from
  cache if such exists."
author: "The Dev Nolus Team <dev@nolus.io>"

outputs:
  image-hash:
    description: ""
    value: |-
      ${{ steps.check-lockfiles.outputs.image-hash }}
  image-id:
    description: ""
    value: |-
      ${{ steps.check-lockfiles.outputs.image-id }}

runs:
  using: "composite"
  steps:
    - id: "rust"
      uses: "./.github/actions/rust-container"
    - env:
        RUST_ID: |-
          ${{ steps.rust.outputs.image-id }}
      id: "check-lockfiles"
      uses: "./.github/actions/build-container"
      with:
        additional-digest-data: |-
          ${{ steps.rust.outputs.image-hash }}
        additional-digest-targets: |-
          ./.github/actions/check-lockfiles-container/
          ./ci/images/check-lockfiles.Containerfile
          ./ci/scripts/check-lockfiles.sh
        build-step: |-
          "build_into_dir" "rust"

          "build" \
            "check-lockfiles" \
            -- \
            --build-arg "rust_id=local-rust" \
            --build-context "local-rust=./.rust-image"
        disable-caching: true
        image-name: "check-lockfiles"
