[package]
name = "tree"
version = "0.1.0"
authors = ["Kiril Mihaylov <k.mihaylov@nolus.io>"]
edition = "2021"
#edition.workspace = true
#license.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = { version = "1", default-features = false, features = ["derive", "alloc"] }
#serde = { workspace = true, features = ["derive"] }
