name: "Build container image"
description: "Action for building a container image, or restoring it from
  cache if such exists."
author: "The Dev Nolus Team <dev@nolus.io>"

outputs:
  image-id:
    description: ""
    value: |-
      ${{ steps.lint.outputs.image-id }}

runs:
  using: "composite"
  steps:
    - id: "rust-ci"
      uses: "./.github/actions/rust-ci-container"
    - id: "lint"
      env:
        RUST_CI_ID: |-
          ${{ steps.rust-ci.outputs.image-id }}
      uses: "./.github/actions/build-container"
      with:
        additional-digest-data: |-
          ${{ steps.rust-ci.outputs.image-hash }}
        additional-digest-targets: |-
          ./.github/actions/lint-container/
          ./ci/images/lint.Containerfile
          ./ci/scripts/lint.internal.sh
          ./ci/scripts/lint.sh
        build-step: |-
          "build" \
            "lint" \
            -- \
            --build-arg "rust_ci_id=${RUST_CI_ID:?}"
        disable-caching: true
        image-name: "lint"
