name: "Build container image"
description: "Action for building a container image, or restoring it from
  cache if such exists."
author: "The Dev Nolus Team <dev@nolus.io>"

outputs:
  image-id:
    description: ""
    value: |-
      ${{ steps.lint.outputs.image-id }}

runs:
  using: "composite"
  steps:
    - id: "rust-stable-ci"
      uses: "./.github/actions/rust-stable-ci-container"
    - env:
        RUST_CI_ID: |-
          ${{ steps.rust-stable-ci.outputs.image-id }}
      run: |-
        set -eu

        . "./.github/build-container.sh"

        "build" \
          "lint" \
          "lint" \
          -- \
          --build-arg "rust_ci_id=${RUST_CI_ID:?}" \
          --tag "localhost/local/lint"

        image_id="$("cat" "./.lint-image-digest")"

        "echo" \
          "image-id<<EOF
        ${image_id:?}
        EOF" \
          >>"${GITHUB_OUTPUT:?}"
      shell: "sh"
