name: "Build container image"
description: "Action for building a container image, or restoring it from
  cache if such exists."
author: "The Dev Nolus Team <dev@nolus.io>"

outputs:
  image-id:
    description: ""
    value: |-
      ${{ steps.lint.outputs.image-id }}

runs:
  using: "composite"
  steps:
    - id: "rust-stable-ci"
      uses: "./.github/actions/rust-stable-ci-container"
    - id: "lint"
      uses: "./.github/actions/build-container"
      with:
        additional-digest-data: |-
          ${{ steps.rust-stable-ci.outputs.image-id }}
        build-step: |-
          "build" \
            "lint" \
            "lint" \
            -- \
            --build-arg "rust_ci_id=${{ steps.rust-stable-ci.outputs.image-id }}" \
            --tag "localhost/local/lint"
        image-friendly-name: "lint"
        image-name: "localhost/local/lint"
