name: "Build container image"
description: "Action for building a container image, or restoring it from
  cache if such exists."
author: "The Dev Nolus Team <dev@nolus.io>"

outputs:
  image-hash:
    description: ""
    value: |-
      ${{ steps.check-formatting.outputs.image-hash }}
  image-id:
    description: ""
    value: |-
      ${{ steps.check-formatting.outputs.image-id }}

runs:
  using: "composite"
  steps:
    - id: "rust"
      uses: "./.github/actions/rust-container"
    - env:
        RUST_ID: |-
          ${{ steps.rust.outputs.image-id }}
      id: "check-formatting"
      uses: "./.github/actions/build-container"
      with:
        additional-digest-data: |-
          ${{ steps.rust.outputs.image-hash }}
        additional-digest-targets: |-
          ./.github/actions/check-formatting-container/
          ./ci/images/check-formatting.Containerfile
        build-step: |-
          "build" \
            "check-formatting" \
            -- \
            --build-arg "rust_id=${RUST_ID:?}"
        disable-caching: true
        image-name: "check-formatting"
