[package]
name = "time-oracle"
version = "0.2.0"
authors = ["The Dev Nolus Team <dev@nolus.io>"]
edition.workspace = true
license.workspace = true

[features]
migrate = []

[dependencies]
platform = { workspace = true }
sdk = { workspace = true, features = ["storage"] }

thiserror = { workspace = true }
serde = { workspace = true, features = ["derive"] }
