[package]
name = "platform"
version = "0.1.2"
authors = ["The Dev Nolus Team <dev@nolus.io>"]
edition.workspace = true
license.workspace = true

[features]
testing = ["sdk/testing"]

[dependencies]
finance = { workspace = true }
sdk = { workspace = true, features = ["cosmos", "cosmos_ibc", "neutron"] }

prost = "0.11.8"
thiserror = { workspace = true }
serde = { workspace = true }
serde-json-wasm = { workspace = true }

[dev-dependencies]
currency = { workspace = true }
finance = { workspace = true, features = ["testing"] }
sdk = { workspace = true, features = ["testing"] }
