lints = { workspace = true }

[package]
name = "lpp-platform"
version = "0.1.0"
authors = ["The Dev Nolus Team <dev@nolus.io>"]
edition.workspace = true
license.workspace = true

[package.metadata.cargo-each]
combinations = [
    { tags = ["ci", "@agnostic"], include-rest = true },
]

[features]
testing = []

[dependencies]
currency = { workspace = true }
finance = { workspace = true }
# oracle-platform = { workspace = true }
platform = { workspace = true }
sdk = { workspace = true, features = ["schema"] }

serde = { workspace = true }
thiserror = { workspace = true}

[dev-dependencies]
platform = { workspace = true, features = ["testing"] }
