name: "Build container image"
description: "Action for building a container image, or restoring it from
  cache if such exists."
author: "The Dev Nolus Team <dev@nolus.io>"

outputs:
  image-hash:
    description: ""
    value: |-
      ${{ steps.rust-ci.outputs.image-hash }}
  image-id:
    description: ""
    value: |-
      ${{ steps.rust-ci.outputs.image-id }}

runs:
  using: "composite"
  steps:
    - id: "rust"
      uses: "./.github/actions/rust-container"
    - id: "cargo-each"
      uses: "./.github/actions/cargo-each-container"
    - env:
        CARGO_EACH_ID: |-
          ${{ steps.cargo-each.outputs.image-id }}
        RUST_ID: |-
          ${{ steps.rust.outputs.image-id }}
        RUST_VERSION: |-
          ${{ inputs.rust-version }}
      id: "rust-ci"
      uses: "./.github/actions/build-container"
      with:
        additional-digest-data: |-
          ${{ steps.cargo-each.outputs.image-hash }}
          ${{ steps.rust.outputs.image-hash }}
        additional-digest-targets: |-
          ./.github/actions/rust-ci-container/
          ./ci/images/rust-ci.Containerfile
        build-step: |-
          "build" \
            "rust-ci" \
            -- \
            --build-arg "cargo_each_id=${CARGO_EACH_ID:?}" \
            --build-arg "rust_id=${RUST_ID:?}"
        disable-caching: true
        image-name: "rust-ci"
