[alias]
lint-prod = "each --tag ci run -- clippy --bins --lib --locked"
lint-test = "each --tag ci run -- clippy --tests --benches --examples"

run-test = "each --tag ci run -- test --all-targets --locked"

[target.wasm32-unknown-unknown]
rustflags = ["-C", "link-arg=-s"]
