[alias]
wasm = "build --release --target wasm32-unknown-unknown"
unit-test = "each --tag ci run test"
schema = "run --example schema"

[target.wasm32-unknown-unknown]
rustflags = ["-C", "link-arg=-s"]
