name: "Build container image"
description: "Action for building a container image, or restoring it from
  cache if such exists."
author: "The Dev Nolus Team <dev@nolus.io>"

inputs:
  profile:
    description: ""
    required: false
  target:
    description: ""
    required: true
  tools-context:
    default: "false"
    description: ""
    required: false
  workspace:
    description: ""
    required: false

runs:
  using: "composite"
  steps:
    - env:
        DOCKER_BUILD_RECORD_UPLOAD: "false"
        SOURCE_DATE_EPOCH: "0"
      id: "build-container"
      uses: "docker/build-push-action@v6"
      with:
        build-contexts: |-
          ${{ (fromJSON(inputs.tools-context) && 'tools=./tools/') || '' }}
        cache-from: |-
          type=gha,scope=${{ inputs.target }}
        cache-to: |-
          type=gha,mode=max,scope=${{ inputs.target }}
        context: "./ci/"
        file: "./Containerfile"
        outputs: "type=docker,rewrite-timestamp=true"
        provenance: false
        tags: |-
          localhost/local/${{ inputs.target }}
        target: |-
          ${{ inputs.target }}
    - env:
        target: |-
          ${{ inputs.target }}
        workspace: |-
          ${{ inputs.workspace }}
      run: |-
        set -eux

        run() {
          "docker" \
            "container" \
            "run" \
            ${{ (inputs.profile && format('--env "PROFILE={0}"', inputs.profile)) || '' }} \
            --tty \
            --volume "./:/src/:ro" \
            "localhost/local/${target}" \
            "${@}"
        }

        case "${workspace?}" in
          ("") "run" ;;
          (*) "run" "${workspace:?}"
        esac
      shell: "sh"
