lints = { workspace = true }

[package]
name = "oracle"
version = "0.5.23"
edition.workspace = true
authors.workspace = true
license.workspace = true

[package.metadata.cargo-each]
combinations = [
    { tags = ["build", "@agnostic"], always-on = ["contract"], include-rest = false },
    { tags = ["ci", "@agnostic"], feature-groups = ["$[contract-and-testing]-or-stubs"], include-rest = false, generics = { "$[contract-and-testing]-or-stubs" = ["contract-and-testing", "stubs"] } },
]
feature-groups = { contract-and-testing = { members = ["contract", "testing"], at-least-one = true, mutually-exclusive = false }, stubs ={ members = ["stub_alarms", "stub_price", "stub_swap"], at-least-one = false, mutually-exclusive = false} }

[lib]
crate-type = ["cdylib", "rlib"]

[features]
contract = [
    "stub_alarms",
    "stub_price",
    "stub_swap",
    "sdk/contract",
    "dep:cosmwasm-std",
    "dep:versioning",
]
stub_alarms = ["dep:currencies", "dep:oracle-platform"]
stub_price = ["dep:oracle-platform"]
stub_swap = ["dep:currencies", "dep:oracle-platform", "testing"]
testing = [
    "stub_alarms",
    "stub_price",
    "stub_swap",
    "currencies/testing",
    "marketprice/testing",
]

[dependencies]
currencies = { workspace = true, optional = true }
currency = { workspace = true }
finance = { workspace = true }
oracle-platform = { workspace = true, optional = true }
platform = { workspace = true }
sdk = { workspace = true }
tree = { workspace = true }
versioning = { workspace = true, optional = true, features = ["protocol_contract"] }

# Required as a dependency by `entry_point` attribute macro
cosmwasm-std = { workspace = true, optional = true }

thiserror = { workspace = true }
serde = { workspace = true, features = ["derive"] }

[dev-dependencies]
currencies = { workspace = true, features = ["testing"] }
currency = { workspace = true, features = ["testing"] }
finance = { workspace = true }
marketprice = { workspace = true, features = ["testing"] }
platform = { workspace = true, features = ["testing"] }
tree = { workspace = true, features = ["testing"] }
