lints = { workspace = true }

[package]
name = "void"
version = "0.0.2"
edition.workspace = true
authors.workspace = true
license.workspace = true

[package.metadata.cargo-each]
combinations = [
    { tags = ["build", "ci", "$net", "$protocol"], include-rest = false, generics = { "$net" = ["net_dev", "net_test", "net_main"], "$protocol" = ["neutron-astroport-usdc_axelar", "osmosis-osmosis-usdc_axelar"] } },
    { tags = ["build", "ci", "$net", "$protocol"], include-rest = false, generics = { "$net" = ["net_dev", "net_test"], "$protocol" = ["osmosis-osmosis-osmo"] } },
    { tags = ["build", "ci", "$net", "$protocol"], include-rest = false, generics = { "$net" = ["net_main"], "$protocol" = ["neutron-astroport-usdc_noble", "osmosis-osmosis-akt", "osmosis-osmosis-all_btc", "osmosis-osmosis-all_sol", "osmosis-osmosis-statom", "osmosis-osmosis-usdc_noble"] } },
]

[lib]
crate-type = ["cdylib", "rlib"]

[features]

[dependencies]
platform = { workspace = true }
sdk = { workspace = true }
timealarms = { workspace = true }
versioning = { workspace = true }

# Required as a dependency by `entry_point` attribute macro
cosmwasm-std = { workspace = true }

serde = { workspace = true, features = ["derive"] }
