lints = { workspace = true }

[package]
name = "swap"
version = "0.1.1"
edition.workspace = true
authors.workspace = true
license.workspace = true

[package.metadata.cargo-each]
combinations = [
    { tags = ["ci", "$net", "$protocol"], feature-groups = ["testing"], always-on = ["astroport", "test"], include-rest = false, generics = { "$net" = ["net_dev", "net_test"], "$protocol" = ["neutron-astroport-usdc_axelar"] } },
    { tags = ["ci", "$net", "$protocol"], feature-groups = ["testing"], always-on = ["astroport", "main"], include-rest = false, generics = { "$net" = ["net_main"], "$protocol" = ["neutron-astroport-usdc_axelar", "neutron-astroport-usdc_noble"] } },
    { tags = ["ci", "$net", "$protocol"], feature-groups = ["testing"], always-on = ["osmosis"], include-rest = false, generics = { "$net" = ["net_dev", "net_test"], "$protocol" = ["osmosis-osmosis-usdc_axelar"] } },
    { tags = ["ci", "$net", "$protocol"], feature-groups = ["testing"], always-on = ["osmosis"], include-rest = false, generics = { "$net" = ["net_dev", "net_test"], "$protocol" = ["osmosis-osmosis-osmo"] } },
    { tags = ["ci", "$net", "$protocol"], feature-groups = ["testing"], always-on = ["osmosis"], include-rest = false, generics = { "$net" = ["net_main"], "$protocol" = ["osmosis-osmosis-statom", "osmosis-osmosis-all_btc", "osmosis-osmosis-all_sol", "osmosis-osmosis-usdc_axelar", "osmosis-osmosis-usdc_noble"] } },
]
feature-groups = { testing = { members = ["testing"], at-least-one = false, mutually-exclusive = false } }

[features]
# Mandatory features
dex-astroport_test = [
    "dep:astroport",
    "sdk/cosmos_proto",
]
dex-astroport_main = [
    "dep:astroport",
    "sdk/cosmos_proto",
]
dex-osmosis = [
    "dep:osmosis-std",
]
dex-test_impl = [
    "dep:astroport",
    "sdk/cosmos_proto",
]

# Optional features
testing = [
    "currency/testing",
    "dex/testing",
    "finance/testing",
    "sdk/cosmos_ibc",
]

[dependencies]
dex = { workspace = true }
oracle = { workspace = true, features = ["stub_swap"] }

currency = { workspace = true }
finance = { workspace = true }
platform = { workspace = true }
sdk = { workspace = true }

astroport = { workspace = true, optional = true }
osmosis-std = { workspace = true, optional = true }
serde = { workspace = true, features = ["derive"] }

[dev-dependencies]
currency = { workspace = true, features = ["testing"] }
platform = { workspace = true, features = ["testing"] }

base64 = { workspace = true, features = ["alloc"] }
