lints = { workspace = true }

[package]
name = "swap"
version = "0.1.2"
edition.workspace = true
authors.workspace = true
license.workspace = true
rust-version.workspace = true

[package.metadata.cargo-each]
combinations = [
    { tags = ["ci", "$dex"], always-on = ["$dex"], feature-groups = ["dex"], include-rest = true, generics = { "$dex" = "dex" } },
]
feature-groups = { dex = { members = ["dex-astroport_main", "dex-astroport_test", "dex-osmosis", "dex-test_impl"], at-least-one = true, mutually-exclusive = true } }

[features]
# Mandatory features
dex-astroport_test = [
    "dep:astroport",
    "sdk/cosmos_proto",
]
dex-astroport_main = [
    "dep:astroport",
    "sdk/cosmos_proto",
]
dex-osmosis = [
    "dep:osmosis-std",
]
dex-test_impl = [
    "dep:astroport",
    "sdk/cosmos_proto",
]

# Optional features
testing = [
    "currency/testing",
    "dex/testing",
    "finance/testing",
    "sdk/cosmos_ibc",
]

[dependencies]
dex = { workspace = true }
oracle = { workspace = true, features = ["stub_swap"] }

currency = { workspace = true }
finance = { workspace = true }
platform = { workspace = true }
sdk = { workspace = true }

astroport = { workspace = true, optional = true }
osmosis-std = { workspace = true, optional = true }
serde = { workspace = true, features = ["derive"] }

[dev-dependencies]
currency = { workspace = true, features = ["testing"] }
platform = { workspace = true, features = ["testing"] }

base64 = { workspace = true, features = ["alloc"] }
