[package]
name = "swap"
version = "0.1.1"
authors = ["The Dev Nolus Team <dev@nolus.io>"]
edition.workspace = true
license.workspace = true

[package.metadata.cargo-each]
combinations = [
    { tags = ["ci", "$net", "$protocol"], feature-groups = ["testing"], always-on = ["astroport", "test"], include-rest = false, generics = { "$net" = ["net_dev", "net_test"], "$protocol" = ["neutron-astroport-usdc_axelar"] } },
    { tags = ["ci", "$net", "$protocol"], feature-groups = ["testing"], always-on = ["astroport", "main"], include-rest = false, generics = { "$net" = ["net_main"], "$protocol" = ["neutron-astroport-usdc_axelar", "neutron-astroport-usdc_noble"] } },
    { tags = ["ci", "$net", "$protocol"], feature-groups = ["testing"], always-on = ["osmosis"], include-rest = false, generics = { "$net" = ["net_dev", "net_test"], "$protocol" = ["osmosis-osmosis-usdc_axelar"] } },
    { tags = ["ci", "$net", "$protocol"], feature-groups = ["testing"], always-on = ["osmosis"], include-rest = false, generics = { "$net" = ["net_dev", "net_test"], "$protocol" = ["osmosis-osmosis-osmo"] } },
    { tags = ["ci", "$net", "$protocol"], feature-groups = ["testing"], always-on = ["osmosis"], include-rest = false, generics = { "$net" = ["net_main"], "$protocol" = ["osmosis-osmosis-statom", "osmosis-osmosis-all_btc", "osmosis-osmosis-all_sol", "osmosis-osmosis-usdc_axelar", "osmosis-osmosis-usdc_noble"] } },
]
feature-groups = { testing = { members = ["testing"], at-least-one = false, mutually-exclusive = false } }

[features]
dex-astroport_test = [
    "dep:astroport",
    "dep:currency",
    "dep:dex",
    "dep:finance",
    "dep:oracle",
    "dep:platform",
    "dep:sdk",
    "sdk/cosmos_ibc",
    "dep:serde",
]
dex-astroport_main = [
    "dep:astroport",
    "dep:currency",
    "dep:dex",
    "dep:finance",
    "dep:oracle",
    "dep:platform",
    "dep:sdk",
    "sdk/cosmos_ibc",
    "dep:serde",
]
dex-osmosis = [
    "dep:currency",
    "dep:dex",
    "dep:finance",
    "dep:oracle",
    "dep:osmosis-std",
    "dep:platform",
    "dep:sdk",
    "sdk/cosmos",
    "dep:serde",
]

testing = [
    "dep:currency",
    "currency/testing",
    "dep:dex",
    "dex/testing",
    "dep:finance",
    "finance/testing",
    "dep:oracle",
    "oracle/stub_swap",
    "dep:platform",
    "dep:sdk",
    "sdk/cosmos_proto",
    "dep:prost",
    "dep:serde",
]

[dependencies]
dex = { workspace = true, optional = true }
oracle = { workspace = true, optional = true }

currency = { workspace = true, optional = true }
finance = { workspace = true, optional = true }
platform = { workspace = true, optional = true }
sdk = { workspace = true, optional = true }

astroport = { workspace = true, optional = true }
osmosis-std = { workspace = true, optional = true }
serde = { workspace = true, optional = true, features = ["derive"] }
prost = { workspace = true, optional = true, features = ["derive", "std"] }

[dev-dependencies]
currency = { workspace = true, features = ["testing"] }
dex = { workspace = true }
finance = { workspace = true }
oracle = { workspace = true }
platform = { workspace = true, features = ["testing"] }
sdk = { workspace = true }

base64 = { workspace = true, features = ["alloc"] }
prost = { workspace = true }
