lints = { workspace = true }

[package]
name = "finance"
version = "0.2.1"
authors = ["The Dev Nolus Team <dev@nolus.io>"]
edition.workspace = true
license.workspace = true

[package.metadata.cargo-each]
combinations = [
    { tags = ["ci", "@agnostic"], include-rest = true },
]

[features]
testing = []

[dependencies]
currency = { workspace = true }
sdk = { workspace = true, features = ["cosmos", "schema"] }

gcd = { workspace = true }
thiserror = { workspace = true }
serde = { workspace = true, features = ["derive"] }

[dev-dependencies]
currency = { workspace = true, features = ["testing"] }
