name: "Build container image"
description: "Action for building a container image, or restoring it from
  cache if such exists."
author: "The Dev Nolus Team <dev@nolus.io>"

inputs:
  additional-digest-data:
    description: ""
    required: false
  additional-digest-targets:
    description: ""
    required: false
  build-step:
    description: ""
    required: true
  image-friendly-name:
    description: ""
    required: true
  image-name:
    description: ""
    required: true

outputs:
  hash:
    description: ""
    value: |-
      ${{ steps.values.outputs.hash }}
  image-id:
    description: ""
    value: |-
      ${{ inputs.image-name }}@${{ steps.build.outputs.image-id }}

runs:
  using: "composite"
  steps:
    - id: "values"
      shell: "sh"
      env:
        additional_digest_data: |-
          ${{ inputs.additional-digest-data || '' }}
        additional_digest_targets: |-
          ${{ inputs.additional-digest-targets || '' }}
        build_step: |-
          ${{ inputs.build-step }}
        image_name: |-
          ${{ inputs.image-name }}
        runner_temp: |-
          ${{ runner.temp }}
      run: |-
        set -eu

        hash_target() (
          case "${#:?}" in
            ("1") ;;
            (*)
              "echo" \
                "This function takes only one argument!" \
                >&2

              exit "1"
          esac

          files="$("find" "${1:?}" -type "f")"

          files="$(
            "sort" <<EOF
        ${files:?}
        EOF
          )"

          hash=""

          while read -r file
          do
            hash="${hash?}
        $("sha256sum" "${file:?}")"
          done <<EOF
        ${files:?}
        EOF

          hash="$(
            "sha256sum" <<EOF
        ${hash?}
        EOF
          )"

          "echo" "${hash:?}"
        )

        additional_targets_hash=""

        case "${additional_digest_targets?}" in
          ("") ;;
          (*)
            while read -r directory
            do
              additional_targets_hash="${additional_targets_hash?}
        $("hash_target" "${directory:?}")"
            done <<EOF
        ${additional_digest_targets:?}
        EOF
        esac

        additional_targets_hash="$(
          "sha256sum" <<EOF
        ${additional_targets_hash?}
        EOF
        )"

        echo "@@@@@@@@@@@ $("hash_target" "./.github/actions/build-container/");$("hash_target" "./.github/build-container.sh");${additional_digest_data?};${additional_targets_hash:?};${build_step:?}"

        hash="$(
          "sha256sum" \
            <<EOF
        $("hash_target" "./.github/actions/build-container/")
        $("hash_target" "./.github/build-container.sh")
        ${additional_digest_data?}
        ${additional_targets_hash:?}
        ${build_step:?}
        EOF
        )"
        hash="${hash%%[[:space:]]*}"
        readonly "hash"

        "echo" \
          "hash<<EOF
        ${hash:?}
        EOF
        key<<EOF
        container-${hash:?}
        EOF
        path<<EOF
        ${runner_temp:?}/container-${hash:?}.tar
        EOF" \
          >>"${GITHUB_OUTPUT:?}"
    - id: "cache-restore"
      uses: "actions/cache/restore@v4"
      with:
        fail-on-cache-miss: false
        key: |-
          ${{ steps.values.outputs.key }}
        lookup-only: false
        path: |-
          ${{ steps.values.outputs.path }}
          ./${{ inputs.image-name }}-image-id
    - if: |-
        steps.cache-restore.conclusion == 'success'
          && steps.cache-restore.outputs.cache-hit == 'true'
      shell: "sh"
      env:
        container_path: |-
          ${{ steps.values.outputs.path }}
        image_friendly_name: |-
          ${{ inputs.image-friendly-name }}
      run: |-
        set -eu

        "docker" \
          "image" \
          "load" \
          --input "${container_path:?}"

        image_id="$("cat" "./.${image_friendly_name:?}-image-id")"

        "echo" \
          "image-id<<EOF
        ${image_id:?}
        EOF" \
          >>"${GITHUB_OUTPUT:?}"

    - id: "build"
      if: |-
        steps.cache-restore.conclusion == 'success'
          && steps.cache-restore.outputs.cache-hit != 'true'
      shell: "sh"
      env:
        container_path: |-
          ${{ steps.values.outputs.path }}
        image_friendly_name: |-
          ${{ inputs.image-friendly-name }}
        image_name: |-
          ${{ inputs.image-name }}
      run: |-
        set -eu

        . "./.github/build-container.sh"

        ${{ inputs.build-step }}

        image_id="$("cat" "./.${image_friendly_name:?}-image-id")"

        "echo" \
          "image-id<<EOF
        ${image_id:?}
        EOF" \
          >>"${GITHUB_OUTPUT:?}"

        "docker" \
          "image" \
          "save" \
          --output "${container_path:?}" \
          "${image_name}@${image_id:?}"
    - if: |-
        steps.cache-restore.conclusion == 'success'
          && steps.cache-restore.outputs.cache-hit != 'true'
      uses: "actions/cache/save@v4"
      with:
        key: |-
          ${{ steps.values.outputs.key }}
        path: |-
          ${{ steps.values.outputs.path }}
          ./${{ inputs.image-friendly-name }}-image-id
