name: "Build optimized"
run-name: "Building optimized version of smart contracts"

on:
  workflow_call:

jobs:
  build_optimized_dev_net:
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@v3"
      - name: "Build optimized binaries for dev-net"
        uses: "./.github/actions/optimized_build"
        with:
          target_net: "dev"
  build_optimized_test_net:
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@v3"
      - name: "Build optimized binaries for test-net"
        uses: "./.github/actions/optimized_build"
        with:
          target_net: "test"
  build_optimized_main_net:
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@v3"
      - name: "Build optimized binaries for main-net"
        uses: "./.github/actions/optimized_build"
        with:
          target_net: "main"
