name: "Smart Contracts"
run-name: "Running checks on smart contracts"

on:
  workflow_call:

jobs:
  perform_checks:
    uses: "./.github/workflows/checks.yaml"
    strategy:
      fail-fast: false
      matrix:
        working_directory: ["protocol"]
        net: ["dev", "test", "main"]
        protocol: ["astroport", "osmosis"]
        include:
          - working_directory: "platform"
          - protocol: "astroport"
            working_directory: "tests"
          - protocol: "osmosis"
            working_directory: "tests"
    name: "Checks [${{ matrix.working_directory }}; ${{ matrix.net }}; ${{ matrix.protocol }}]"
    with:
      target_net: "${{ matrix.net }}"
      target_protocol: "${{ matrix.protocol }}"
      protocols_list: 'astroport,osmosis'
      working_directory: "${{ matrix.working_directory }}"
