name: Smart Contracts
run-name: "Building smart contracts, triggered by ${{ github.actor }}"

on:
  workflow_dispatch:
    inputs:
      optimized_build:
        description: "Check and build optimized binaries."
        type: "boolean"
        required: true
        default: false
  push:
    branches:
      - "main"
    tags:
      - '*'
    paths-ignore:
      - "README.md"
  pull_request:
    branches:
      - "main"
    paths-ignore:
      - "README.md"

env:
  CARGO_TERM_COLOR: "always"

jobs:
  check_formatting:
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@v3"
      - uses: "./.github/actions/rust_cache"
      - uses: "./.github/actions/check_formatting"
  check_codebase:
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@v3"
      - uses: "./.github/actions/rust_cache"
      - uses: "./.github/actions/check_codebase"
  audit_dependencies:
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@v3"
      - uses: "./.github/actions/rust_cache"
      - uses: "./.github/actions/audit_dependencies"
  linting:
    runs-on: "ubuntu-latest"
    needs:
      - "check_formatting"
      - "check_codebase"
      - "audit_dependencies"
    steps:
      - uses: "actions/checkout@v3"
      - uses: "./.github/actions/rust_cache"
      - name: "Run linter"
        shell: "sh"
        run: "./lint.sh"
  code_coverage:
    runs-on: "ubuntu-latest"
    needs:
      - "linting"
    steps:
      - uses: "actions/checkout@v3"
      - uses: "./.github/actions/rust_cache"
      - uses: "./.github/actions/code_coverage"
  test_release_profile:
    runs-on: "ubuntu-latest"
    needs:
      - "linting"
    steps:
      - uses: "actions/checkout@v3"
      - uses: "./.github/actions/rust_cache"
      - name: "Run tests in release profile"
        shell: "sh"
        run: "cargo test --release"
  check_wasm:
    runs-on: "ubuntu-latest"
    needs:
      - "linting"
    steps:
      - uses: "actions/checkout@v3"
      - uses: "./.github/actions/rust_cache"
      - shell: "sh"
        run: "cargo install cargo-workspaces"
      - shell: "sh"
        run: "cargo install cosmwasm-check"
      - name: "Building WASM binaries"
        shell: "sh"
        run: "cargo workspaces exec cargo build --target wasm32-unknown-unknown"
      - name: "Checking WASM binaries"
        shell: "sh"
        run: "cosmwasm-check --available-capabilities staking,stargate,cosmwasm_1_1,iterator,neutron ./target/wasm32-unknown-unknown/debug/*.wasm"
  build_optimized_test_net:
    runs-on: "ubuntu-latest"
    needs:
      - "code_coverage"
      - "test_release_profile"
      - "check_wasm"
    if: "github.ref_type == 'tag' || github.event.inputs.optimized_build"
    steps:
      - uses: "actions/checkout@v3"
      - name: "Build optimized for test-net"
        uses: "./.github/actions/optimized_build"
        with:
          target_net: "test"
  build_optimized_main_net:
    runs-on: "ubuntu-latest"
    needs:
      - "code_coverage"
      - "test_release_profile"
      - "check_wasm"
    if: "github.ref_type == 'tag' || github.event.inputs.optimized_build"
    steps:
      - uses: "actions/checkout@v3"
      - name: "Build optimized binaries for main-net"
        uses: "./.github/actions/optimized_build"
        with:
          target_net: "main"
