name: Smart Contracts
run-name: "Building smart contracts, triggered by ${{ github.actor }}"

on:
  workflow_dispatch:
  push:
    branches:
      - "main"
    tags:
      - '*'
    paths-ignore:
      - "README.md"
  pull_request:
    branches:
      - "main"
    paths-ignore:
      - "README.md"

env:
  CARGO_TERM_COLOR: "always"

jobs:
  check-formatting:
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@v3"
      - uses: "./.github/actions/rust-cache"
      - uses: "./.github/actions/check-formatting"
  check-codebase:
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@v3"
      - uses: "./.github/actions/rust-cache"
      - uses: "./.github/actions/check-codebase"
  audit-dependencies:
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@v3"
      - uses: "./.github/actions/rust-cache"
      - uses: "./.github/actions/audit-dependencies"
  linting:
    runs-on: "ubuntu-latest"
    needs:
      - "check-formatting"
      - "check-codebase"
      - "audit-dependencies"
    steps:
      - uses: "actions/checkout@v3"
      - uses: "./.github/actions/rust-cache"
      - name: "Run linter"
        shell: "sh"
        run: "./lint.sh"
  code-coverage:
    runs-on: "ubuntu-latest"
    needs:
      - "linting"
    steps:
      - uses: "actions/checkout@v3"
      - uses: "./.github/actions/rust-cache"
      - uses: "./.github/actions/code-coverage"
  test-release-profile:
    runs-on: "ubuntu-latest"
    needs:
      - "linting"
    steps:
      - uses: "actions/checkout@v3"
      - uses: "./.github/actions/rust-cache"
      - name: "Run tests in release profile"
        shell: "sh"
        run: "cargo test --release"
  check-wasm:
    runs-on: "ubuntu-latest"
    needs:
      - "linting"
    steps:
      - uses: "actions/checkout@v3"
      - uses: "./.github/actions/rust-cache"
      - shell: "sh"
        run: "cargo install cargo-workspaces"
      - shell: "sh"
        run: "cargo install cosmwasm-check"
      - name: "Building WASM binaries"
        shell: "sh"
        run: "cargo workspaces exec cargo build --target wasm32-unknown-unknown"
      - name: "Checking WASM binaries"
        shell: "sh"
        run: "cosmwasm-check --available-capabilities staking,stargate,cosmwasm_1_1,iterator,neutron ./target/wasm32-unknown-unknown/debug/*.wasm"
  build-optimized:
    runs-on: "ubuntu-latest"
    needs:
      - "code-coverage"
      - "test-release-profile"
      - "check-wasm"
    if: "github.ref_type == 'tag'"
    steps:
      - uses: "actions/checkout@v3"
      - shell: "sh"
        run: |
          build() {
            sudo docker run --rm -v "$(pwd)":/code -v "$(pwd)/artifacts_${1}_net":/code/artifacts --mount type=volume,source="$(basename \"$(pwd)\")_cache",target=/code/target --mount type=volume,source=rustup_dir_cache,target=/usr/local/rustup --mount type=volume,source=cargo_dir_cache,target=/usr/local/cargo --mount type=volume,source=registry_cache,target=/usr/local/cargo/registry cosmwasm/workspace-optimizer:0.12.11 --env ALT_NET_SYMBOLS=${2}
          }

          check_sizes() {
            find artifacts_${1}_net/ -size +800k | wc -l | read large_files_count

            if !test "$large_files_count" = "0";
              then exit 1;
            fi
          }

          copy_deploy_script() {
            sudo cp scripts/deploy-contracts-genesis.sh artifacts_${1}_net/
          }
      - name: "Run workspace-optimizer docker image for test-net"
        shell: "sh"
        run: "build test 1"
      - name: "Check for test-net WASM binaries larger than allowed limit"
        shell: "sh"
        run: "check_sizes test"
      - name: "Copy deployment script to test-net artifacts directory"
        shell: "sh"
        run: "copy_deploy_script test"
      - name: "Run workspace-optimizer docker image for main-net"
        shell: "sh"
        run: "build main 0"
      - name: "Check for main-net WASM binaries larger than allowed limit"
        shell: "sh"
        run: "check_sizes main"
      - name: "Copy deployment script to main-net artifacts directory"
        shell: "sh"
        run: "copy_deploy_script main"
      - name: "Archive test-net artifacts"
        uses: "actions/upload-artifact@v3"
        with:
          name: "optimized-binaries-test-net"
          path: "artifacts_test_net/"
      - name: "Archive main-net artifacts"
        uses: "actions/upload-artifact@v3"
        with:
          name: "optimized-binaries-main-net"
          path: "artifacts_main_net/"
